# Generated by Django 4.2.1 on 2023-06-17 16:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TombstoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('tombstone', 'سنگ قبر'), ('inscription', 'کتیبه'), ('sandblast', 'سندبلاست'), ('wholesale', 'عمده فروشی')], max_length=50)),
                ('image', models.ImageField(upload_to='cover_tombstone/')),
                ('price', models.PositiveIntegerField(blank=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.PositiveIntegerField(blank=True, null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
