# Generated by Django 4.2.1 on 2023-06-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('image', models.ImageField(upload_to='cover_inscription/')),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='SandblastModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('image', models.ImageField(upload_to='cover_sandblast/')),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='WholesaleModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('image', models.ImageField(upload_to='cover_wholesale/')),
            ],
            bases=('product.basemodel',),
        ),
    ]
