# Generated by Django 4.2.1 on 2023-06-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tombstonemodel',
            name='group',
            field=models.CharField(choices=[('tombstone', 'سنگ قبر'), ('wholesale', 'عمده فروشی')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
