# Generated by Django 4.2.1 on 2023-06-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tombstonemodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombstonemodel',
            name='group',
            field=models.CharField(choices=[('tombstone', 'سنگ قبر'), ('inscription', 'کتیبه'), ('sandblast', 'سندبلاست'), ('wholesale', 'عمده فروشی')], max_length=50),
        ),
    ]
