# Generated by Django 4.2.1 on 2023-05-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='shor_description',
            new_name='short_description',
        ),
    ]
