# Generated by Django 4.2.1 on 2023-05-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_shor_description_productmodel_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='title',
            new_name='name',
        ),
    ]
