# Generated by Django 4.2.1 on 2023-05-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_specificationsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.productmodel'),
        ),
    ]
